module.exports = {
  "status device": "Get-ComputerInfo",
  "check os": "Get-CimInstance Win32_OperatingSystem",
  "check cpu": "Get-CimInstance Win32_Processor",
  "check memory": "Get-CimInstance Win32_PhysicalMemory",
  "check bios": "Get-CimInstance Win32_BIOS",
  "check network": "Get-NetAdapter",
  "check wifi": "Get-Get-NetAdapter -Name \"Wi-Fi\"",
  "check gpu": "Get-CimInstance Win32_VideoController",
  "check sound": "Get-CimInstance Win32_SoundDevice",
  "check disk space": "Get-PSDrive -PSProvider FileSystem",
  "list processes": "Get-Process",
  "list services": "Get-Service",
  "check users": "Get-LocalUser",
  "check uptime": "(Get-CimInstance Win32_OperatingSystem).LastBootUpTime",
  "list disks": "Get-PhysicalDisk",
  "check battery": "Get-WmiObject Win32_Battery",
  "wifi status": "Get-NetAdapter | Where-Object {$_.Status -eq 'Up'}",
  "ping google": "Test-Connection google.ca",
  // Add more mappings here
};